apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jcasc
  namespace: jenkins
data:
  credentials.yaml: |
    credentials:
      system:
        domainCredentials:
          - credentials:
              - usernamePassword:
                  scope: GLOBAL
                  id: github-token
                  username: ${github_user}
                  password: ${github_pat}
                  description: GitHub PAT
  seed-job.yaml: |
    jobs:
      - script: >
          job('seed-job') {
            description('Job to generate pipeline for Django project')
            scm {
              git {
                remote {
                  url('${github_repo_url}')
                  credentials('github-token')
                }
                branches('*/lesson-8-9')
              }
            }
            steps {
              dsl {
                text('''pipelineJob("goit-django-docker") {
                  definition {
                    cpsScm {
                      scm {
                        git {
                          remote {
                            url("${github_repo_url}")
                            credentials("github-token")
                          }
                          branches("*/lesson-8-9")
                        }
                      }
                    }
                  }
                }''')
              }
            }
          }
