controller:
  admin:
    username: admin
    password: admin123
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - credentials-binding:latest
    - github:latest
    - docker-workflow:latest
    - job-dsl:latest
  JCasC:
    configScripts:
      credentials: |
        (залиш як шаблон з твоїм values.yaml)
