applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: ${github_repo_url}
      path: charts/django-app
      targetRevision: lesson-8-9
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: <https://kubernetes.default.svc>
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: ${github_repo_url}
    username: ${github_user}
    password: ${github_pat}

repoConfig:
  insecure: "true"
  enableLfs: "true"