{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .source.repoURL | quote }}
    path: {{ .source.path | quote }}
    targetRevision: {{ .source.targetRevision | quote }}
    helm:
      valueFiles:
      {{- range .source.helm.valueFiles }}
        - {{ . | quote }}
      {{- end }}
  destination:
    server: {{ .destination.server | quote }}
    namespace: {{ .destination.namespace | quote }}
  syncPolicy:
    automated:
      prune: {{ .syncPolicy.automated.prune }}
      selfHeal: {{ .syncPolicy.automated.selfHeal }}
    {{- if .syncPolicy.syncOptions }}
    syncOptions:
    {{- range .syncPolicy.syncOptions }}
      - {{ . }}
    {{- end }}
    {{- end }}
---
{{- end }}