{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: {{ .url }}
  username: {{ .username }}
  password: {{ .password }}
  insecure: "{{ $.Values.repoConfig.insecure }}"
  enableLfs: "{{ $.Values.repoConfig.enableLfs }}"
---
{{- end }}